# -*- coding: utf-8 -*-
"""plot for surevy and choropleth map.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1u3APOZ8PeFb0UV7z_f2fwe9RISHMsim2
"""

from google.colab import files
uploaded = files.upload()

import pandas as pd


df_data=pd.read_csv("Topic_Survey_Assignment.csv")

df_data=df_data.rename(columns={0 : 'Type'})
df=df_data.set_index('Type')
df= round(((df/2233.0)*100),2)
df=df.sort_values(by=['Very interested', 'Somewhat interested','Not interested'], ascending=False)
df.head(6)

import matplotlib.pyplot as plt
import numpy as np


n_groups = 6


fig, ax = plt.subplots()

index = np.arange(n_groups)
bar_width = 0.3

opacity = 0.8
error_config = {'ecolor': '0.3'}



rects1 = ax.bar(index, df['Very interested'].values, bar_width,
                alpha=opacity, color='#5cb85c',
                error_kw=error_config,
                label='Very Interested')

rects2 = ax.bar(index+ bar_width,df['Somewhat interested'].values, bar_width,
                alpha=opacity, color='#5bc0de',
                error_kw=error_config,
                label='Somewhat Interested')

rects3 = ax.bar(index + bar_width+bar_width, df['Not interested'].values, bar_width,
                alpha=opacity, color='#d9534f',
                error_kw=error_config,
                label='Not interested')

ax.set_xlabel('Type')
ax.set_ylabel('Scores')
ax.set_title('Scores by Interest')
ax.set_xticks(index + bar_width/2)
ax.set_xticklabels(('Big Data', 'Data Analysis', 'Data Journalism', 'Data Visualization', 'Data Learning', 'Data Analysis'))
ax.legend((rects1[0], rects2[0],rects3[0]), ('Very Interested', 'Somewhat Interested','Not interested'))

def autolabel(rects):
    """
    Attach a text label above each bar displaying its height
    """
    for rect in rects:
        height = rect.get_height()
        ax.text(rect.get_x() + rect.get_width()/3., 1.05*height,
                '%d' % int(height),
                ha='center', va='bottom')

autolabel(rects1)
autolabel(rects2)
autolabel(rects3)

fig.tight_layout()
plt.show()



from google.colab import files
uploaded = files.upload()

import pandas as pd
import folium

df_san=pd.read_csv("Police_Department_Incidents_-_Previous_Year__2016_ (1).csv",engine='python',encoding='utf-8')

df =df_san.rename(columns={'PdDistrict':'Neighborhood'})

df= df.groupby(['Neighborhood']).count()

df=df.drop(['IncidntNum','Category','Descript','DayOfWeek','Date','Time','Resolution','Address','X','Y','PdId'], axis=1)

df=df.rename(columns={'Location':'Count'})
df=df.reset_index()
df.head(11)

from google.colab import files
uploaded = files.upload()

latitude = 37.77
longitude = -122.42

# create map and display it
sanfran_map = folium.Map(location=[latitude, longitude], zoom_start=12)

# display the map of San Francisco
sanfran_map

sanfran_geo = r'san-francisco.geojson'

san= folium.Choropleth(geo_data=sanfran_geo,data=df,
                           columns=(['Neighborhood', 'Count']),
                           key_on='feature.properties.DISTRICT',
                           fill_color='YlOrRd',
                           fill_opacity=0.7,
                           line_opacity=0.2,
                           legend_name='Crime rates in San Francisco'
                           ).add_to(sanfran_map)
sanfran_map

